services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= sytombk
      - POSTGRES_DB= CatalogDb
    restart: always
    ports:
        - 5432:5432
    volumes: 
      - postgres_catalog:/var/lib/postgresql/data/
  
  catalog.api:
    depends_on:
      - catalogdb
    ports:
      - "8080"
      - "8081"